version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: dev_postgres_container
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./src/database/docker-images/postgres:/var/lib/postgresql/data
    environment:
      - NODE_ENV=development
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
